//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI_KMC_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class infParameter
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> mainttime { get; set; }
        public string userID { get; set; }
        public string name { get; set; }
        public Nullable<int> scope { get; set; }
        public string value { get; set; }
        public string comments { get; set; }
        public int sectionID { get; set; }
        public Nullable<int> helpcontextid { get; set; }
        public Nullable<short> isaudited { get; set; }
        public Nullable<int> datatype { get; set; }
        public Nullable<short> allowpersonalvalues { get; set; }
        public Nullable<short> allowgroupvalues { get; set; }
        public Nullable<short> allowplantvalues { get; set; }
        public Nullable<int> parametertype { get; set; }
        public string obsolete { get; set; }
        public string enumeration { get; set; }
        public Nullable<int> businessClassID { get; set; }
        public byte[] versionTimeStamp { get; set; }
        public string configurationchangereference { get; set; }
        public string configurationnotes { get; set; }
    }
}
