//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI_KMC_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class mscMessageSystem
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> mainttime { get; set; }
        public string userID { get; set; }
        public string name { get; set; }
        public Nullable<int> sectionID { get; set; }
        public string adapter { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> mAPDatasetID { get; set; }
        public Nullable<int> direction { get; set; }
        public byte[] versionTimeStamp { get; set; }
    }
}
